added solution to the hw
AnyaRatusnyak/concert-tickets-hw pull request #13
Opened 2024-10-01 13:48 UTC by AnyaRatusnyak

2024-10-01 15:20 UTC, Alexmansar requested changes
@AnyaRatusnyak Hi) in general good solution, just few comments)

2024-10-01 15:20 UTC, Alexmansar commented on src/main/java/TicketService.java
> +    private static ArrayList<Map<String, Object>> loadTicketsToArrayList(ApplicationContext context, String path) {
List<Map<String, Object>>, not ArrayList<Map<String, Object>>

2024-10-01 15:20 UTC, Alexmansar commented on src/main/java/TicketService.java
> +    }
please, use it in the separate class.

2024-10-01 15:20 UTC, Alexmansar commented on src/main/java/dao/UserDataBaseDaoImpl.java
> +            Transaction transaction = session.beginTransaction();
do we need it? we use annotation here. Please, check it)

2024-10-02 07:50 UTC, AnyaRatusnyak commented on src/main/java/TicketService.java
> +    private static ArrayList<Map<String, Object>> loadTicketsToArrayList(ApplicationContext context, String path) {
Good morning ) Sorry

2024-10-02 07:50 UTC, AnyaRatusnyak commented on src/main/java/TicketService.java
> +    }
Ok

2024-10-02 07:53 UTC, AnyaRatusnyak commented on src/main/java/dao/UserDataBaseDaoImpl.java
> +            Transaction transaction = session.beginTransaction();
Oh! My mistake (( Annotation @Transactional include session.beginTransaction() and commit() and rollback().
Thank you ! Good day

2024-10-02 08:38 UTC, Alexmansar approved these changes
@AnyaRatusnyak Hi)) Good job) could be merged) have a nice day too)

2024-10-04 13:47 UTC, merged