findByStadiumSector method
AnyaRatusnyak/concert-tickets-hw pull request #3
Opened 2024-09-03 14:41 UTC by Tolyaspit

Please check changes and approve it!

2024-09-03 14:44 UTC, Alexmansar requested changes
@Tolyaspit @AnyaRatusnyak hi, please check the comment)

2024-09-03 14:44 UTC, Alexmansar commented on src/TicketService.java
> +    }
is it a part of second task..?I think its about first))

2024-09-04 12:59 UTC, Alexmansar approved these changes
@Tolyaspit @AnyaRatusnyak Hi, good jod, could be merged as well)

2024-09-04 13:04 UTC, AnyaRatusnyak approved these changes
Good job)

2024-09-04 14:21 UTC, merged